=== FinnishCustoms-SuomenTulli/account-register-information-update/schemas/information_update-v3-other.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "required": [
    "creationDateTime",
    "senderBusinessId"
  ],
  "definitions": {
    "account": {
      "type": "object",
      "description": "Account",
      "required": [
        "id",
        "openingDate",
        "roles"
      ],
      "properties": {
        "id": {
          "$ref": "#/definitions/accountIdentification"
        },
        "openingDate": {
          "description": "Account opening date.",
          "$ref": "#/definitions/date"
        },
        "closingDate": {
          "description": "Account closing date.",
          "$ref": "#/definitions/date"
        },
        "roles": {
          "type": "array",
          "description": "Account related roles.",
          "minItems": 1,
          "items": {
            "$ref": "#/definitions/role"
          }
        },
        "accountPurpose": {
          "type": "string",
          "description": "The purpose of the account, if applicable.",
          "enum": ["customer_asset_account"]
        }
      }
    },
    "accountIdentification": {
      "type": "object",
      "description": "Account identification.",
      "oneOf": [{
          "required": [
            "iban"
          ]
        },
        {
          "required": [
            "other"
          ]
        }
      ],
      "properties": {
        "iban": {
          "type": "string",
          "description": "IBAN account number.",
          "examples": [
            "FI2753564444694907"
          ]
        },
        "other": {
          "$ref": "#/definitions/otherAccountIdentification"
        }
      }
    },
    "businessId": {
      "type": "string",
      "description": "Business id or VAT number",
      "examples": [
        "0245442-8",
        "FI02454428",
        "SE999999999901",
        "NL999999999B01"
      ],
      "minLength": 4,
      "maxLength": 20,
      "pattern": "[A-Z|0-9|-]+"
    },
    "customer": {
      "type": "object",
      "description": "Customer",
      "required": [
        "startDate"
      ],
      "properties": {
        "startDate": {
          "description": "Customer start date.",
          "$ref": "#/definitions/date"
        },
        "endDate": {
          "description": "Customer end date.",
          "$ref": "#/definitions/date"
        }
      }
    },
    "date": {
      "type": "string",
      "examples": [
        "2019-08-17"
      ]
    },
    "legalPerson": {
      "type": "object",
      "description": "Legal person which is always either a natural person (privatePerson) or a juridical person (organisation).",
      "properties": {
        "organisation": {
          "$ref": "#/definitions/organisation"
        },
        "privatePerson": {
          "$ref": "#/definitions/privatePerson"
        }
      },
      "oneOf": [{
          "required": [
            "organisation"
          ]
        },
        {
          "required": [
            "privatePerson"
          ]
        }
      ]
    },
    "organisation": {
      "type": "object",
      "description": "Juridical person.",
      "required": [
        "name",
        "registrationNumber"
      ],
      "properties": {
        "registrationNumber": {
          "type": "object",
          "required": [
            "number",
            "type"
          ],
          "properties": {
            "number": {
              "type": "string",
              "description": "Organisation registration number"
            },
            "type": {
              "$ref": "#/definitions/registrationNumberType"
            }
          }
        },
        "registrationAuthority": {
          "type": "string",
          "description": "Registration authority.",
          "maxLength": 70
        },
        "registrationDate": {
          "description": "Registration date.",
          "$ref": "#/definitions/date"
        },
        "name": {
          "type": "string",
          "description": "Organisation name.",
          "maxLength": 300
        }
      }
    },
    "otherAccountIdentification": {
      "type": "object",
      "description": "Other than IBAN account number.",
      "required": [
        "id",
        "description"
      ],
      "properties": {
        "id": {
          "type": "string",
          "description": "Account identification.",
          "maxLength": 200
        },
        "description": {
          "type": "string",
          "description": "Description of the used account identification type.",
          "maxLength": 200
        }
      }
    },
    "privatePerson": {
      "type": "object",
      "description": "Natural person.",
      "anyOf": [{
          "required": [
            "fullName",
            "birthDate",
            "hetu"
          ]
        },
        {
          "required": [
            "fullName",
            "birthDate",
            "nationalities"
          ]
        },
          {
          "required": [
            "fullName",
            "birthDate",
            "hetu",
            "nationalities"
          ]
        }
      ],
      "properties": {
        "fullName": {
          "type": "string",
          "description": "Full name.",
          "examples": [
            "Korhonen, Juhani Antti"
          ],
          "maxLength": 140
        },
        "birthDate": {
          "description": "Date of birth.",
          "$ref": "#/definitions/date"
        },
        "nationalities": {
          "description": "Nationalities",
          "type": "array",
          "items": {
            "type": "string",
            "minLength": 2,
            "maxLength": 2
          },
          "examples": [
            ["FI", "RU"]
          ]
        },
        "hetu": {
          "type": "string",
          "description": "Personal identity code (Finnish hetu).",
          "examples": [
            "151080-999L"
          ]
        }
      }
    },
    "role": {
      "type": "object",
      "description": "Role",
      "required": [
        "startDate",
        "type",
        "legalPersonReference"
      ],
      "properties": {
        "startDate": {
          "description": "Role start date",
          "$ref": "#/definitions/date"
        },
        "endDate": {
          "description": "Role end date.",
          "$ref": "#/definitions/date"
        },
        "type": {
          "type": "string",
          "description": "Role type.",
          "enum": ["owner", "access"]
        },
        "legalPersonReference": {
          "description": "Legal person identifier",
          "$ref": "#/definitions/uuidv4"
        }
      }
    },
    "registrationNumberType": {
      "type": "string",
      "oneOf": [
        {
          "description": "Finnish business id (Y-tunnus)",
          "type": "string",
          "const": "businessId"
        },
        {
          "description": "Registration number of a Finnish association",
          "type": "string",
          "const": "associationRegistrationNumber"
        },
        {
          "description": "Generic registration number",
          "type": "string",
          "const": "registrationNumber"
        }
      ]
    },
    "uuidv4": {
      "type": "string",
      "description": "Unambiguous identifier used for record. UUIDv4.",
      "examples": [
        "91e8c532-71e1-4c4f-bf30-ceec6160ece0"
      ]
    }
  },
  "properties": {
    "creationDateTime": {
      "$id": "#/properties/creationDateTime",
      "description": "Creation date and time of the message.",
      "$ref": "#/definitions/date"
    },
    "senderBusinessId": {
      "$id": "#/properties/senderBusinessId",
      "description": "Sender business id or VAT number.",
      "$ref": "#/definitions/businessId"
    },
    "legalPersons": {
      "$id": "#/properties/legalPersons",
      "type": "object",
      "additionalProperties": {
        "$ref": "#/definitions/legalPerson"
      },
      "description": "Legal persons."
    },
    "customers": {
      "$id": "#/properties/customers",
      "type": "object",
      "additionalProperties": {
        "$ref": "#/definitions/customer"
      },
      "description": "Customers"
    },
    "accounts": {
      "$id": "#/properties/accounts",
      "type": "object",
      "additionalProperties": {
        "$ref": "#/definitions/account"
      },
      "description": "Accounts"
    }
  }
}

=== FinnishCustoms-SuomenTulli/account-register-information-update/examples/report-update-v3-other.json
{
  "creationDateTime": "2020-03-06T12:50:12.374",
  "senderBusinessId": "8428746-6",
  "legalPersons": {
    "5d892fac-07f0-465f-ab6a-af88a1d922ba": {
      "organisation": {
        "registrationAuthority": "PRH",
        "registrationNumber": 
        {
        	"number": "4276521-2",
        	"type": "businessId"
        },
        "registrationDate": "1965-05-09",
        "name": "Firma Oy"
      }
    },
    "6cd7cc3f-6de1-4583-a572-895613e71130": {
      "privatePerson": {
        "fullName": "Fredlund, Eeva-Sofia",
        "hetu": "010659-9744",
        "birthDate": "1959-06-01"
      }
    },
    "cc695a85-32a9-4cf7-88a3-9b635f5c03b5": {
      "privatePerson": {
        "fullName": "Heimlander, Raimond Ernst",
        "hetu": "100368-970P",
        "birthDate": "1968-03-14"
      }
    },
    "edfb750c-26e6-44fc-b857-bd0caa06b74e": {
      "privatePerson": {
        "fullName": "Suppala, Atsalea Achieng",
        "hetu": "211156-926R",
        "birthDate": "1956-11-21"
      }
    },
    "e4a623ca-0ad7-4f3b-9b9e-81109b33da27": {
      "privatePerson": {
        "fullName": "Onnenlehto, Jarl-Olof Lassi",
        "birthDate": "1969-12-20",
        "nationalities": ["SE", "FI"]
      }
    },
    "a092893a-14e5-4b8d-adaf-80c1b7be95b6": {
      "privatePerson": {
        "fullName": "Utukka, Emelia Terella",
        "birthDate": "1970-07-25",
        "nationalities": ["SE", "FI"]
      }
    },
    "82911739-6f97-439e-b561-22fac327b774": {
      "privatePerson": {
        "fullName": "Tiiri, Lawrence Samuel",
        "hetu": "070280-9137",
        "birthDate": "1980-02-07"
      }
    },
    "3b153d44-4caa-4feb-bdd1-a91b6b1759ce": {
      "privatePerson": {
        "fullName": "Cooper, Anna-Roosa Vivika",
        "hetu": "241100A948X",
        "birthDate": "2000-11-24"
      }
    },
    "ebab0a47-00a7-4d56-aa63-028102d7a329": {
      "privatePerson": {
        "fullName": "Långfors, Pirjo-Kaarina Daniela",
        "hetu": "020783-900C",
        "birthDate": "1983-07-02"
      }
    },
    "279aeafc-528e-4f81-b79c-ecc8b0aafd4c": {
      "organisation": {
        "registrationAuthority": "PRH",
        "registrationDate": "1989-08-25",
        "registrationNumber": 
        {
        	"number": "0245442-8",
        	"type": "associationRegistrationNumber"
        },
        "name": "Yhdistys Ry"
      }
    },
    "a51b4ee8-1ec1-48ae-8d14-5948118a9659": {
      "privatePerson": {
        "fullName": "Ehnqvist, Taisa Annele",
        "hetu": "180971-9328",
        "birthDate": "1971-09-18"
      }
    },
    "1b420512-acad-4ce4-be24-f73f0e078e8b": {
      "privatePerson": {
        "fullName": "Järvenoja, Lise-Lott Herta",
        "hetu": "250578-980W",
        "birthDate": "1978-05-25"
      }
    },
    "70904e2d-87b8-4e3b-8421-b0907a62dd96": {
      "privatePerson": {
        "fullName": "Miettinen, Matti Pekka",
        "hetu": "030289-1179",
        "birthDate": "1989-03-02"
      }
    }
  },
  "customers": {
    "5d892fac-07f0-465f-ab6a-af88a1d922ba": {
      "startDate": "2000-12-31"
    },
    "e4a623ca-0ad7-4f3b-9b9e-81109b33da27": {
      "startDate": "1990-10-10"
    },
    "a092893a-14e5-4b8d-adaf-80c1b7be95b6": {
      "startDate": "2012-10-26"
    },
    "82911739-6f97-439e-b561-22fac327b774": {
      "startDate": "2010-08-26"
    },
    "3b153d44-4caa-4feb-bdd1-a91b6b1759ce": {
      "startDate": "2014-02-04",
      "endDate": "2019-07-03"
    },
    "ebab0a47-00a7-4d56-aa63-028102d7a329": {
      "startDate": "2012-12-30"
    },
    "279aeafc-528e-4f81-b79c-ecc8b0aafd4c": {
      "startDate": "2012-12-30"
    },
    "70904e2d-87b8-4e3b-8421-b0907a62dd96": {
      "startDate": "2017-01-05"
    }
  },
  "accounts": {
    "6c035985-976f-4fa6-afcb-e1745eb58f9d": {
      "id": {
        "iban": "FI8371356610003253"
      },
      "openingDate": "2016-11-30",
      "roles": [{
        "legalPersonReference": "5d892fac-07f0-465f-ab6a-af88a1d922ba",
        "startDate": "2016-11-30",
        "type": "owner"
      }]
    },
    "b7b8ab37-9480-46aa-a3fc-5a946ce39d13": {
      "id": {
        "other": {
          "id": "HR8320134556",
          "description": "other account id"
        }
      },
      "openingDate": "2010-10-30",
      "closingDate": "2019-01-21",
      "roles": [{
          "legalPersonReference": "e4a623ca-0ad7-4f3b-9b9e-81109b33da27",
          "startDate": "2010-11-12",
          "endDate": "2019-01-21",
          "type": "owner"
        },
        {
          "legalPersonReference": "a092893a-14e5-4b8d-adaf-80c1b7be95b6",
          "startDate": "2013-09-20",
          "endDate": "2019-01-21",
          "type": "access"
        }
      ]
    },
    "116f9e18-2ba5-45de-9b88-ab5767c4e6e7": {
      "id": {
        "iban": "FI3749321479839355"
      },
      "openingDate": "2018-10-11",
      "roles": [{
        "legalPersonReference": "70904e2d-87b8-4e3b-8421-b0907a62dd96",
        "startDate": "2018-10-11",
        "type": "owner"
      }],
      "accountPurpose": "customer_asset_account"
    }
  }
}
